version: "3.8"

services:
  app:
    build: .
    container_name: dimdimapp
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: senha123
      DB_NAME: dimdim
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - rede-dimdim

  db:
    image: mysql:8.0
    container_name: mysql-dimdim
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: dimdim
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - rede-dimdim

volumes:
  mysql-data:

networks:
  rede-dimdim:
